---
require:
  - rubocop-factory_bot
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - tmp/*
    - vendor/**/*
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Max: 120

Lint/Debugger:
  Enabled: true
  Exclude: []

Metrics/BlockLength:
  Exclude: ["describe", "context"]
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 20

Rails/FindEach:
  Enabled: true
  Exclude: []
Rails/Output:
  Enabled: true
  Exclude: []
Rails/OutputSafety:
  Enabled: false
  Exclude: []

Style/Documentation:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
