version: "3.8"

name: yrp-services
services:
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 54320:5432

volumes:
  postgres:
