// TypesFromSerializers CacheKey af6f591bab7b6ba2921857dad196ca72
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  id: unknown
  createdAt: string | Date
  email: string
  updatedAt: string | Date
}
